name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run YAML linting
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: |
            *.yml
            .github/workflows/*.yml

      - name: Setup linting environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true
          post-cleanup: none  # breaks otherwise

      - name: Check formating
        run: |
          make ci
        shell: bash -el {0}


  Up-Down:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare secrets
        run: |
          mkdir -p .ci/secrets
          echo db-password > .ci/secrets/db-password
          echo pgadmin-password > .ci/secrets/pgadmin-password

      - name: Prepare empty volumes
        run: |
          mkdir -p .ci/volumes/minio/data
          mkdir -p .ci/volumes/pgadmin/data
          mkdir -p .ci/volumes/postgres/data
          mkdir -p .ci/volumes/rabbitmq/data
          mkdir -p .ci/volumes/redis/data
          mkdir -p .ci/volumes/reev-static/data

      - name: Prepare configuration
        run: |
          cp .env.ci .env

          mkdir -p .ci/config/nginx
          cp utils/nginx/nginx.conf .ci/config/nginx
          mkdir -p .ci/config/pgadmin
          cp utils/pgadmin/servers.json .ci/config/pgadmin

      - name: Bring up and shut down services
        uses: isbang/compose-action@v2.0.0
        with:
          compose-file: docker-compose.yml
          compose-flags: |
            --env-file .env
        env:
          DB_PASSWORD: "password"
